spring.application.name=hostel-management

spring.datasource.url=jdbc:postgresql://localhost:5432/hostel_management
spring.datasource.username=postgres
spring.datasource.password=YOUR_POSTGRES_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false